#!/bin/sh
### BEGIN INIT INFO
# Provides:          gogs
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts gogs
# Description:       Starts gogs Daemon
### END INIT INFO

# Author: Timo Martins <timo@seoer-it.de>

# this start-script works only to ubuntu 15.04 causes on upstart....
# I just added the runlevel-command to this scripts the original-start script is from someone of https://deb.packager.io/gh/pkgr/gogs (I forgot to save his name, I really sry, if I found it, it will push it again for the right props : / ) 


echo "This job runs via upstart, invoking upstart now..."
exec initctl $1 gogs

